import { Inter } from "next/font/google";
import "./globals.css";
import Header from "../../components/Header";
import ColorPallete from "../../components/ColorPallete";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "canvas demo ...",
  description: "Generated by next app and redux"
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" dir="rtl">
      <body className=" w-full flex flex-col">
       
        
            {children} 
         
      </body>
    </html>
  );
}
