import { Inter } from 'next/font/google'
import './globals.css'
import Footer from '../../components/Footer'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'canvas demo ...',
  description: 'Generated by next app and redux',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" dir='rtl'>
      <body className={inter.className}>
        <Footer/>
        {children}
      </body>
    </html>
  )
}
